# Builds url downloader with Windows/MSCV and Linux/GCC.

name: CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
 
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        config:
          - name: "Windows / MSVC"
            os: windows-latest
            c_compiler: cl
            cxx_compiler: cl
 
          - name: "Linux / GCC"
            os: ubuntu-latest
            c_compiler: gcc
            cxx_compiler: g++
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
 
      - name: Setup (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc g++ ninja-build
 
      - name: Configure CMake
        run: >
          cmake -S ${{ github.workspace }}
          -B ${{ github.workspace }}/build
          -DCMAKE_C_COMPILER=${{ matrix.config.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
 
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel
